package org.kurochan.scaptive_portal.openflow.model

object FlowTTL {

  val AUTHORIZED_OUT_HARD = 90
  val AUTHORIZED_OUT_IDLE = AUTHORIZED_OUT_HARD

  val UNAUTHORIZED_OUT_HARD = AUTHORIZED_OUT_HARD / 3
  val UNAUTHORIZED_OUT_IDLE = AUTHORIZED_OUT_IDLE / 3

  val UNAUTHORIZED_DROP_HARD = AUTHORIZED_OUT_HARD / 4
  val UNAUTHORIZED_DROP_IDLE = AUTHORIZED_OUT_IDLE / 4
}
