package org.kurochan.scaptive_portal.openflow.model

object FlowTTL {

  val AUTHORIZED_OUT_HARD = 180
  val AUTHORIZED_OUT_IDLE = AUTHORIZED_OUT_HARD

  val UNAUTHORIZED_OUT_HARD = 15
  val UNAUTHORIZED_OUT_IDLE = UNAUTHORIZED_OUT_HARD

  val UNAUTHORIZED_DROP_HARD = 12
  val UNAUTHORIZED_DROP_IDLE = UNAUTHORIZED_DROP_HARD
}
